services:
  server:
    container_name: server_monservice
    build:
      context: .
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - web
    stdin_open: true
    tty: true
    command: pnpm start

networks:
  web:
    external: true
